// NnConfigGenKit.swift
// Generated by NnProjectGenerator on May 5, 2024

import Files
import Foundation

public enum NnConfigGen {
    public func saveConfig<Config: NnConfig>(_ config: Config) throws {
        let configFilePath = ConfigPathFactory.makeConfigFilePath(projectName: config.projectName)
        let configFile = try Folder.home.createFileIfNeeded(at: configFilePath)
        let encoder = JSONEncoder.prettyOutput()
        let configData = try encoder.encode(config)
        
        try configFile.write(configData)
    }
    
    public func loadConfig<Config: NnConfig>(projectName: String) throws -> Config {
        let configFilePath = ConfigPathFactory.makeConfigFilePath(projectName: projectName, withHomeDirectory: true)
        let configFile = try File(path: configFilePath)
        let data = try configFile.read()
        let decoder = JSONDecoder()
        
        return try decoder.decode(Config.self, from: data)
    }
}


// MARK: - Dependencies
public protocol NnConfig: Codable {
    var projectName: String { get }
}


// MARK: - Extension Dependencies
public extension JSONEncoder {
    static func prettyOutput() -> JSONEncoder {
        let encoder = JSONEncoder()
        encoder.outputFormatting = .prettyPrinted
        
        return encoder
    }
}
